apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis
spec:
  secretName: redis-tls
  dnsNames:
    - redis-master.dbs.svc.cluster.local
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer